name: Auto-Extend Universe
on:
  schedule:
    - cron: "15 2 * * *"     # täglich um 02:15 UTC (anpassen wie gewünscht)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Rebuild extended_universe.txt
        run: python tools/auto_extend.py
      - name: Commit updated list
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/extended_universe.txt || true
          git commit -m "auto-extend universe" || echo "no changes"
          git push
