name: Mars CI

on:
  schedule:
    - cron: "0,30 * * * *"     # alle 30 Minuten
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    # Umgebungsvariablen für Rotation/Umfang je Lauf
    env:
      ROTATION_SLOTS: "6"      # Anzahl Rotations-Segmente (z.B. 4/6/8)
      MAX_UNIVERSE: "200"      # max. Ticker pro Lauf (200 ist stabil)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Generate alerts.json
        run: python run_report_json.py > alerts.json

      - name: Publish alerts.json to docs (with robots.txt)
        run: |
          mkdir -p docs
          cp alerts.json docs/alerts.json
          echo "User-agent: *" > docs/robots.txt
          echo "Disallow: /" >> docs/robots.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/alerts.json docs/robots.txt || true
          git commit -m "update alerts" || echo "no changes"
          git push
