name: Mars CI – MAIN

on:
  schedule:
    - cron: "2 * * * *"   # stündlich Minute 02 (UTC)
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # ---- DST-Gate: nur 07/12/17 Europe/Berlin weiterlaufen ----
      - name: Time gate (Europe/Berlin → 07/12/17 only)
        id: timegate
        run: |
          TZ=Europe/Berlin
          HOUR=$(TZ=$TZ date +%H)
          if [ "$HOUR" = "07" ] || [ "$HOUR" = "12" ] || [ "$HOUR" = "17" ]; then
            echo "continue=true" >> $GITHUB_OUTPUT
          else
            echo "continue=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if not scheduled Berlin hour
        if: steps.timegate.outputs.continue == 'false'
        run: echo "Skipping run (not 07/12/17 Berlin time)." && exit 0

      # ---- Live-Kurse ziehen (Snapshot) ----
      - name: Pull live prices (EUR snapshot)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python tools/live_data.py
          echo "===== prices_eur_snapshot.csv (Top 10) ====="
          sed -n '1,10p' data/prices_eur_snapshot.csv || true

      # ---- Engine: schreibt docs/alerts.json + data/alerts_out.json ----
      - name: Run Alert Engine (run_alerts.py)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          mkdir -p docs
          python tools/run_alerts.py
          echo "===== docs/alerts.json (erste 40) ====="
          sed -n '1,40p' docs/alerts.json || true

      # ---- Commit & Push (force im CI) ----
      - name: Commit & push docs/alerts.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/alerts.json || true
          if git diff --cached --quiet; then
            echo "Keine Änderungen zu committen."
          else
            git commit -m "CI(main): update alerts.json ($(date -u +'%Y-%m-%dT%H:%MZ'))"
            git push origin HEAD:main --force
          fi
