name: Mars CI

on:
  schedule:
    - cron: "0 * * * *"      # jede volle Stunde
    - cron: "0 12 * * *"     # täglich 12:00 Uhr
    - cron: "0 17 * * *"     # täglich 17:00 Uhr
  workflow_dispatch:          # erlaubt manuelles Auslösen

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Mars Hub
        run: python mars_hub.py

      - name: Save alerts.json
        run: |
          mkdir -p docs
          cp alerts.json docs/
      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/alerts.json
          git commit -m "Update alerts.json"
          git push
