name: Mars CI Main

on:
  schedule:
    - cron: '0 * * * *'     # jede volle Stunde (UTC)
    - cron: '0 12 * * *'    # täglich 13:00 CET-Sommer / 12:00 CET-Winter (UTC)
    - cron: '0 17 * * *'    # täglich 18:00 CET-Sommer / 17:00 CET-Winter (UTC)
  workflow_dispatch: {}     # manuell startbar

permissions:
  contents: write           # wir committen docs/alerts.json

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # >>> Kernschritt: HUB erzeugt die Alerts und schreibt direkt in docs/
      - name: Generate alerts.json (via mars_hub.py)
        shell: bash
        run: |
          set -e
          mkdir -p docs
          python mars_hub.py > docs/alerts.json
          # Safety: Datei muss existieren und nicht leer sein
          test -s docs/alerts.json

      # Optionales Preview im Log (hilft beim Debuggen)
      - name: Preview first lines of docs/alerts.json
        run: sed -n '1,120p' docs/alerts.json || true

      # Commit nur, wenn sich der Inhalt geändert hat
      - name: Commit & push docs/alerts.json
        shell: bash
        run: |
          if git diff --quiet -- docs/alerts.json; then
            echo "No changes in docs/alerts.json — nothing to commit."
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/alerts.json
          git commit -m "CI: update alerts.json ($(date -u +'%Y-%m-%dT%H:%MZ'))"
          git push
